@echo off
set ENGINE_PATH=K:\unreal\UE_4.27
::set ENGINE_PATH=E:\Unreal\UE_4.27

set PROJECT_NAME=Ue_Hx
set PACKAGE_DIR=C:\UE4_Packaging\%PROJECT_NAME%
set EDITOR_BUILD_CONFIG=Editor
set EDITOR_BUILD_TARGET=Development
set EDITOR_BUILD_PLATFORM=Win64
set PROJECT_FILE=C:\dev\haxe\Ue_Hx\%PROJECT_NAME%.uproject

"%ENGINE_PATH%\Engine\Build\BatchFiles\Build.bat" %PROJECT_NAME%%EDITOR_BUILD_CONFIG% %EDITOR_BUILD_PLATFORM% %EDITOR_BUILD_TARGET% %PROJECT_FILE% -waitmutex