#pragma once

#include "CoreMinimal.h"
#include "Engine/GameInstance.h"
#include <../_hxlib/xUnreal.h>
#include "AppGInst.generated.h"

/* 
* =============================================
* Generated by xUnreal - don't edit!
* =============================================
*/

static bool haxeRunning = false;
static HaxeObject haxeMainInstance;

UCLASS()
class UAppGInst : public UGameInstance
{
	GENERATED_BODY()
	
public:
	UAppGInst();
    virtual void Init() override;
    virtual void Shutdown() override;



private:
	HaxeObject hxInst;
};
