#include "AppGInst.h"

/* 
* =============================================
* Generated by xUnreal - don't edit!
* =============================================
*/

void onHaxeException(const char* info)
{
    XUnrealMain_stopHaxeThreadIfRunning(false);	// stop the haxe thread immediately

    if (GEngine != NULL)
        GEngine->AddOnScreenDebugMessage(-1, 15.f, FColor::Red, info);
}

UAppGInst::UAppGInst()
{
}

void UAppGInst::Init()
{
	Super::Init();

    if (!haxeRunning)
    {
        XUnrealMain_initializeHaxeThread(onHaxeException); // start the haxe thread
        haxeRunning = true;
    }

    if (!haxeMainInstance)
    {
        XUnrealMain_unreal_GEngine_init(TCHAR_TO_UTF8(*FPaths::LaunchDir()));
        haxeMainInstance = XUnrealMain_new();
    }

    if (hxInst)
        XUnrealMain_releaseHaxeObject(hxInst); 

    if (!hxInst)
    {
        hxInst = XUnrealMain_AppGInst_new();
        XUnrealMain_unreal_GameInstance_setOwner(hxInst, this);
    }

    if (hxInst)
        XUnrealMain_AppGInst_Init(hxInst);
}

void UAppGInst::Shutdown()
{
    if (hxInst)
    {
        XUnrealMain_AppGInst_Shutdown(hxInst);
        XUnrealMain_releaseHaxeObject(hxInst); 
        hxInst = NULL;
    }

    if (haxeMainInstance)
        XUnrealMain_releaseHaxeObject(haxeMainInstance); // when we're done with our object we can tell the haxe-gc we're finished

    //Main_stopHaxeThreadIfRunning(true); // stop the haxe thread but wait for any scheduled events to complete
    Super::Shutdown();
}

/////////////////////////////////////////////////////////////////////////////////////